### ISSUE TITLE
toString methods for JobData and subclasses

### ISSUE THREAD

**Issue by ayoung012** [ssardina-agts/agtcity-server#11]
massim.protocol.scenario.city.data.JobData
massim.protocol.scenario.city.data.MissionData
massim.protocol.scenario.city.data.AuctionJobData

**Comment by ssardina** [comment]
@ayoung012 I never saw this one that you added! Somehow I cannot assign this to you, github is not showing me any ids...

**Comment by ayoung012** [comment]
Resolved in PR #14
