### ISSUE TITLE
Shops cover all items from jobs?

### ISSUE THREAD

**Issue by ssardina** [ssardina-agts/agtcity-server#19]
Hi @ayoung012 !

Just one question comes to me. When we did the new server and brought back items from 2017 code, did we make sure that items in shop will cover the requirements of jobs? That is, you can buy all items needed in shops and don't worry about resources?

Do you know or remember this?

**Comment by ayoung012** [comment]
I just checked the implementation, and all BASE items are available in shops, none are missed in any case. Remember though that jobs require assembled items, which are not available in shops or resource nodes, and can only be acquired by assembling base items.

The makeup of complex assembled items is randomly generated, and the construction tree can be configured to be within some maximum level. (A graph level of > 2 may require complex items to combined to produce more complex assembled items)

**Comment by ssardina** [comment]
> I just checked the implementation, and all BASE items are available in shops, none are missed in any case. Remember though that jobs require assembled items, which are not available in shops or resource nodes, and can only be acquired by assembling base items.
> 

phew! Good news, thanks for checking!

> The makeup of complex assembled items is randomly generated, and the construction tree can be configured to be within some maximum level. (A graph level of > 2 may require complex items to combined to produce more complex assembled items)

yes, yes. Correct. Complex items is one of the main interesting features of this game. I just wanted to check that the raw material is covered in shops already (so use of resource nodes are not a must)

Thanks!
