### ISSUE TITLE
Wrong calculation of job rewards

### ISSUE THREAD

**Issue by ssardina** [ssardina-agts/agtcity-server#20]
So, the reward of jobs are not well calculated in terms of the cost of items, because it seems the cost of items give 0 always!! So the job is not scaled:

![image](https://user-images.githubusercontent.com/2368384/118993494-e74b4680-b9c8-11eb-8926-53876b49e35e.png)

This is bad because a job will not be worth doing it.

When I print I get this:

![image](https://user-images.githubusercontent.com/2368384/118994053-5c1e8080-b9c9-11eb-94f8-03e9a649bea6.png)

@ayoung012 , any clue why items would not have cost at this point?

**Comment by ayoung012** [comment]
The items are not given a cost when attributed to a job because the reward calculation is not calculated from any made up cost. It is for the shops to decide the cost.

My guess is the rewardModMin and rewardModMax in https://www.github.com/ssardina-agts/agtcity-server/tree/master/server%2Fconf%2Fgenerate%2Fjobs%2FdiverseJobs.json has been tuned with the assumption that items will only be collected from resource nodes. We should try increasing these values. And see if that improves the reward.

**Comment by ssardina** [comment]
I don't think so Adam. The code above suggest that the reward is calculated based on the cost of items and the scaled up by a constant (say 1.5x). See line 625 and before it... the reward is adding the cost of items, and it makes sense. That was the way it was done in 2017 server. Otherwise there is no way to guarantee that a job is worth doing it.

I did another print and I think it is taking cost 0 because they are all complex items!! It is failing to compute the cost of building those items.

**Comment by ayoung012** [comment]
Upon closer inspection of the job generator
https://www.github.com/ssardina-agts/agtcity-server/tree/master/server%2Fsrc%2Fmain%2Fjava%2Fmassim%2Fscenario%2Fcity%2Futil%2FGenerator.java

rewardScale config Param will likely have a more dramatic impact on the reward.

You can also see the cost assigned to a particular item in a particular shop in the shop generation method in the above file.

**Comment by ssardina** [comment]
Exactly!!

See the code here is meant to compute the cost of the job in terms of the value of items:

![image](https://user-images.githubusercontent.com/2368384/118997741-3b0b5f00-b9cc-11eb-9b5a-d27e79f0d346.png)

but the value of items come to zero always, maybe because they are complex?

Now the shops charge different prices for the same item? what is the value of an item?

**Comment by ssardina** [comment]
It is clear the price is in a shop for an item; teh item itself has no price:

![image](https://user-images.githubusercontent.com/2368384/118998268-a6edc780-b9cc-11eb-99b1-553992c7a824.png)

Now what is then the `item.getValue()`?

**Comment by ayoung012** [comment]
Ah very interesting... Maybe I missed something here that was supposed to determine the value of complex items by crawling through the construction tree?

**Comment by ayoung012** [comment]
I will have to check the 2017 implementation again

**Comment by ssardina** [comment]
But you never touched that I think... See what happens when we create an item:

![image](https://user-images.githubusercontent.com/2368384/118998800-15328a00-b9cd-11eb-89fa-6a1214990efc.png)

That is giving zero. Looking at Git, that line you seem to have added it... and says: "add monetary value to items in shops"..

yeah I think it is here..

**Comment by ssardina** [comment]
and it is using `.stream()`, which I know you love it! ;-) :laughing:

**Comment by ayoung012** [comment]
Is it because the config is missing valueMin, valueMax for item:

https://www.github.com/ssardina-agts/agtcity-server/tree/master/server%2Fconf%2Fgenerate%2Fgenerate-manyItems.json

I can't see how.. it should default to 10, 100.. I will look closer tomorrow.

**Comment by ssardina** [comment]
Good nite, I am going offline too.. :sleeping_bed:

**Comment by ssardina** [comment]
found the issue:

![image](https://user-images.githubusercontent.com/2368384/119001904-bfabac80-b9cf-11eb-9bfd-72c40d0f4f9b.png)

good nite and thanks for joining at this hours....

**Comment by ayoung012** [comment]
https://youtu.be/M5d7vygUPoQ
😅
