### ISSUE TITLE
GH: Connection between locations not found

### ISSUE THREAD

**Issue by ssardina** [ssardina-agts/agtcity-server#6]
At the start of a sim I get:

```
[ ERROR  ]  ##   GH: Connection between locations not found
[ NORMAL  ]  ##   Simulation at step 0
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector (file:/home/ssardina/git/soft/agents/MAC-AgtCity/2018-rmit/agtcity-server.git/server/target/server-2020-1.0-jar-with-dependencies.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by ayoung012** [comment]
GH stands for Graph Hopper, and is probably related to the initial path planning caching for road based agents in the Map. My guess is some OpenStreetMap network links are not reachable, hence the error. This error occurs already with 2018 server on Paris, so I'll assume we shouldn't worry about it.
The xml warnings at a guess are exclusive to openjdk11, and related to the updated xml dependencies. I cannot reproduce on these on openjdk8

**Comment by ssardina** [comment]
Good, not important to handle this then. Thanks for the explanation.
