### ISSUE TITLE
Tracking items of an entity: List or Set?

### ISSUE THREAD

**Issue by ssardina** [ssardina-agts/agtcity-server#7]
`EntityData` tracks the items an agent hs with `List<ItemAmountData>`.

@ayoung012 , shouldn't this be `Set<ItemAmountData>` as the order on how they are store is irrelevant?

Otherwis this makes it difficult to compare changes and we have to do an ad-hoc equals to compare two sets of has items.

**Comment by ssardina** [comment]
@ayoung012 has go around this limitation by doing this equal method:

The collector done is very cool!

```java
static def equal(list1 : List<ItemAmountData>, list2 : List<ItemAmountData>) : boolean {
		if (list1 === null && list2 === null) {
			return true
		} else if (list1 === null || list2 === null) {
			return false
		} else if (list1.size() != list2.size()) {
			return false
		}

		val intoMap : Collector<ItemAmountData, ?, Map<String, Integer>> =
			Collectors.toMap([i|i.getName()], [ i | i.getAmount()])
		val map1 = list1.stream().collect(intoMap)
		val map2 = list2.stream().collect(intoMap)

		if (map1.equals(map2)) {
			return true
		} else {
			return false
		}
	}
```

**Comment by ayoung012** [comment]
Yep, was about to say. Better this hacky equality method than trying to re-engineer protocol and the server.

**Comment by ayoung012** [comment]
Note that when we change protocol (eg private to public) we still technically don't stray from supporting the true competition.

However if we changed this to a set, we would then have to modify the server to produce a set here too, maybe tweak the XML gen.. etc. Even though we have already modified the server to have items in shops, it is my preference not to take this as a free pass to start making further modifications unless absolutely necessary.

**Comment by ssardina** [comment]
mmm it is a good point what you stated. But consider that competition is gone unfortunately. And we are already dealing with items which is a HUGE change.

I think sticking to a less good server just because it keeps "historical" is too demanding for us, we get NO benefit on our side. The old competition won't happen.

BTW, we are only changing the CLIENT right? So if we change `protocol` it is fine right?

**Comment by ayoung012** [comment]
While items is indeed a huge change, it is exact in its implementation as it was in the 2017 server.

**Comment by ayoung012** [comment]
Yes, totally ok with just changing protocol. If only in the interests of reducing scope creep.

**Comment by ayoung012** [comment]
Remember your strong NO stance on re-engineering this part of the client communication process:

Client: XML -> CityStepPercept -> EIS.iilang.Percept

https://github.com/ssardina-agts/agtcity-sarl-mw/wiki

If we change Lists to Sets in the protocol data, you are heading full speed ahead into this territory.

**Comment by ssardina** [comment]
OK I take the point, I get it now the change from `List` to `Set` is a lot and will require changes in server so we may not want that.

We will have utilities in `Util` package to do fancy comparisons. 

Now the extension for `.equal()` and `.hasCode()` remains right?

**Comment by ayoung012** [comment]
Alternatively Comparators could be used, to keep this all together and all in middleware space.

Chapter 3 & 4 are worth a read:
https://www.baeldung.com/java-comparator-comparable#comparator

**Comment by ayoung012** [comment]
After more consideration I think just adding equals and hasCode to the protocol data classes will be best.

**Comment by ssardina** [comment]
good. yes I have just done that in the new server commit. I will try it now

**Comment by ssardina** [comment]
Won't change data structures, as discussed in #8
