### ISSUE TITLE
.equals() and .hashCode() missing in data classes

### ISSUE THREAD

**Issue by ssardina** [ssardina-agts/agtcity-server#8]
This makes it difficult to track changes from data to data. At least we need to add them to

* WayPointData
* ActioNData
* ItemAmount (once we also address #7 

@ayoung012 do you agree?

**Comment by ayoung012** [comment]
I support this, as long as it doesn't mean further changes to the **server** package. I think it's best to isolate changes to the **protocol** package only.

**Comment by ayoung012** [comment]
Keep in mind why we replaced our entity classes in the first place - maintainability

**Comment by ssardina** [comment]
Correct. But all the classes we use are in `protocol`, nothing on the server itself.

given that we have control on our server now, it's OK to do updates on it if it will make the whole thing better, cleaner and more efficient right?

**Comment by ayoung012** [comment]
Yes, we are using protocol in the mw and it is our version. We can do what we like to it, use different versions for the client and the server even! And it will not affect the actual server - the client and the server are two seperate java projects.

In line with my comment on the other issue: 
Note that when we change protocol (eg attributes private to public, add some convenience hashCode and equal methods, etc) we still technically don't stray from supporting the true competition server.

However if we changed the actual attribute data structures (eg from list to set), we we cross over to modifying the competition from how it was built. Whether they did this intentionally or unintentionally is not for me to say. But the point remains.

We would then have to modify the server to produce a set here too, maybe tweak the XML gen.. etc. Even though we have already modified the server to have items in shops, it is my preference not to take this as a free pass to start making further modifications unless absolutely necessary.

Every step we take away from the comp is a backtracking step if we ever go back to the 2017 server. Not saying we will do that this iteration, but weigh up the sacrifice of that option in the future with this efficiency improvement you propose.

**Comment by ayoung012** [comment]
So to make clear my preference:
Add equals and hashCode methods to data - YES

BUT to contain the fallout damage to the server, avoid changing data structures of actual Data attributes, even if there is an efficiency cost (eg conversion of data to Map in order to compare inside the equals method).

**Comment by ssardina** [comment]
agre. Done in 0915df70bca8af425488cdcda30a26ddd7d63233
